export const RECEIVE_AUTHORIZATION_KEY_REQUEST =
	'RECEIVE_AUTHORIZATION_KEY_REQUEST';
export const RECEIVE_AUTHORIZATION_KEY_SUCCESS =
	'RECEIVE_AUTHORIZATION_KEY_SUCCESS';
export const CREATE_TRANSACTION_REQUEST = 'CREATE_TRANSACTION_REQUEST';
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS';
export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST';
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS';
export const GET_TRANSACTIONS_ERROR = 'GET_TRANSACTIONS_ERROR';
export const RECEIVE_AUTHORIZATION_KEY = 'RECEIVE_AUTHORIZATION_KEY';
